Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"


    (1..2).each do |i|
        config.vm.define "webserver#{i}" do |node|
            node.vm.provider :virtualbox do |vb_config|
                vb_config.name = "Web Server #{i}"
                vb_config.memory = "256"
                vb_config.cpus = 1
            end
            node.vm.provision :file, source: "webapps/" , destination: "/home/vagrant/webapps"
            node.vm.hostname = "webserver#{i}"
            node.vm.network "private_network", ip: "192.168.50.1#{i}"
            node.vm.provision :shell, path: "scripts/webserver.sh"
        end
    end

  # Configs for LoadBalancer
    config.vm.define :loadbalancer do |lb_config|
        lb_config.vm.provider :virtualbox do |vb_config|
            vb_config.name = "Apache httpd LoadBalancer"
            vb_config.memory = "512"
            vb_config.cpus = 1
        end
        lb_config.vm.provision :file, source: "loadbalancer/" , destination: "/home/vagrant/lb"

        lb_config.vm.hostname = "loadb"
        lb_config.vm.network "private_network", ip: "192.168.50.30"
        lb_config.vm.provision :shell, path: "scripts/loadbalancer_mod_jk.sh"
        # lb_config.vm.provision :shell, path: "scripts/loadbalancer_mod_proxy.sh"
    end
end
